plugins {
    id 'java'
}

group = 'net.maxurhino.doodley_editor'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform("org.junit:junit-bom:${project.junitBomVersion}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // [lwjgl]

    implementation platform("org.lwjgl:lwjgl-bom:${project.lwjglVersion}")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-assimp"
    implementation "org.lwjgl:lwjgl-freetype"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.lwjgl:lwjgl::${project.lwjglNatives}"
    implementation "org.lwjgl:lwjgl-assimp::${project.lwjglNatives}"
    implementation "org.lwjgl:lwjgl-freetype::${project.lwjglNatives}"
    implementation "org.lwjgl:lwjgl-glfw::${project.lwjglNatives}"
    implementation "org.lwjgl:lwjgl-openal::${project.lwjglNatives}"
    implementation "org.lwjgl:lwjgl-opengl::${project.lwjglNatives}"
    implementation "org.lwjgl:lwjgl-stb::${project.lwjglNatives}"

    // [maths]

    implementation "org.joml:joml:${project.jomlVersion}"
    implementation "org.joml:joml-primitives:${project.joml_primitivesVersion}"

    // [image loading]

    implementation ("org.apache.xmlgraphics:batik-transcoder:${project.batikVersion}") {
        exclude group: "xml-apis", module: "xml-apis"
    }
    implementation ("org.apache.xmlgraphics:batik-codec:${project.batikVersion}") {
        exclude group: "xml-apis", module: "xml-apis"
    }

    implementation "javazoom:jlayer:${project.jlayerVersion}"

    // [data loading]
    implementation "com.google.code.gson:gson:${project.gsonVersion}"
    implementation "org.yaml:snakeyaml:${project.snakeyamlVersion}"

    // [annotations]
    implementation "org.jspecify:jspecify:${project.jspecifyVersion}"
}

test {
    useJUnitPlatform()
}